### ISSUE TITLE
How to specify audience during the token exchange?

### ISSUE THREAD

**Issue by rizwan95** [auth0-samples/auth0-ios-swift-siwa-samples#6]
While using webAuth() API, there is a provision to specify the audience and scopes. Similarly, there should be an API to specify the audience and scopes during the native token exchange process.

**Comment by kvdesa** [comment]
The `tokenExchange()` method has the `scope` and `audience` parameters, but they are set as `nil` by default. You can start sending them normally.
Instead of:
`
Auth0.authentication().tokenExchange(withAppleAuthorizationCode: appleAuthorizationCode)
`
You do:
`
Auth0.authentication().tokenExchange(withAppleAuthorizationCode: appleAuthorizationCode, scope: NetworkConstants.Value.scope, audience: NetworkConstants.Value.audience)
`

**Comment by Widcket** [comment]
Thanks @kvdesa, closing this one.
